baseURL = "https://getpaidwithsylwia.com"
languageCode = "en"
defaultContentLanguage = "en"

title = "Sylwia Gumienna | Links"
copyright = ""

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Sylwia Gumienna"
  headline = "Affiliate Marketing Made Simple - Get Paid With Sylwia"
  image = "img/profile.jpg"  # path relative to static directory

  links = [
    { link = { href = "https://docs.google.com/document/d/1X-aKj3trqLIxQW718jD4LlyiwGmhoow_1hgKzG5DjTU/edit", text = "3 Professional Courses ($0.00)" } },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    { instagram = { href = "https://instagram.com/gumiennaklara", text = "Instagram" } },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    { youtube = { href = "https://www.youtube.com/c/SylwiasMarketing", text = "YouTube" } },
    { email = { href = "mailto:gumiennaklara@hotmail.co.uk", text = "Email" } },

  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
