baseURL = "https://getpaidwithsylwia.com"
languageCode = "en"
defaultContentLanguage = "en"

title = "Sylwia Gumienna | Links"
copyright = ""

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Sylwia Gumienna"
  headline = "Affiliate Marketing Made Simple - Get Paid With Sylwia"
  image = "img/profilepic2.jpg"  # path relative to static directory

  links = [ 
    { link = { href = "https://getpaidwithsylwia.com/free", text = "Today $0.00 - Get Instant Access To 3 Professional Courses For Free" } },
    { link = { href = "https://escapeplanis.com/lp/escapeplanis1iftf/3/BKGJLMAD9Q", text = "Grow Your Email List With This 100% Free Training" } },
    { link = { href = "https://sylwia-reviews.netlify.app", text = "Check Out My Epic Reviews" } },
    { link = { href = "https://marketingwithsylwia.com/", text = "Check Out My Website" } },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    { facebook = { href = "https://www.facebook.com/sylwia.gumienna.12/", text = "Facebook" } },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    { instagram = { href = "https://instagram.com/gumiennaklara", text = "Instagram" } },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    { linkedin = { href = "https://www.linkedin.com/in/sylwia-gumienna-a84708326/?trk=opento_sprofile_details", text = "LinkedIn" } },
    # { mastodon = "https://mastodon.instance/@username" },
    { medium = { href = "https://medium.com/@sylwiagumienna/about", text = "Medium" } },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    { youtube = { href = "https://www.youtube.com/c/SylwiasMarketing", text = "YouTube" } },
    { email = { href = "mailto:gumiennaklara@hotmail.co.uk", text = "Email" } },

  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
